---
- name: Test Azure Credentials
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: Verify Azure SDK availability
      command: "{{ ansible_python_interpreter }} -c 'import azure.mgmt.resource; print(\"Azure SDK OK\")'"

    - name: Check authentication by listing resource groups
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "rg-buget"
